version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/src:cached
      - node_modules:/src/node_modules
    working_dir: "/src"
    command: yarn dev
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - API_DOMAIN="localhost:80"
      - STORAGE_URL=https://file.meltyblood-typelumina-fan.com
    networks:
      - nuxt

volumes:
  node_modules:


networks:
  nuxt:
